steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['build', '-t', 'gcr.io/$PROJECT_ID/gatsby-blog-cloud-run', './client']

    # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gatsby-blog-cloud-run']

    # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'gatsby-blog-cloud-run',
        '--image',
        'gcr.io/$PROJECT_ID/gatsby-blog-cloud-run',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--quiet',
        '--allow-unauthenticated',
      ]

images:
  - gcr.io/$PROJECT_ID/gatsby-blog-cloud-run
